name: 'Terraform Deploy to GCP'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Apply to GCP'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Decode GCP service account key
        run: echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > account.json

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="credentials_file=account.json"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="credentials_file=account.json"