...
    - name: Debug Secret Value
      run: |
        echo "PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}"

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var="credentials_file=account.json" -var="project_id=${{ secrets.GCP_PROJECT_ID }}"

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="credentials_file=account.json" -var="project_id=${{ secrets.GCP_PROJECT_ID }}"
