name: 'Terraform Deploy to GCP'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Upload service account key
      run: echo "${{ secrets.GCP_SA_KEY }}" > account.json

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var="credentials_file=account.json" -var="project_id=${{ secrets.GCP_PROJECT_ID }}"

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="credentials_file=account.json" -var="project_id=${{ secrets.GCP_PROJECT_ID }}"